name: my-app

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./server/Dockerfile.server
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    command: npm run dev:server
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${APP_PORT}/ || exit 1"]
      interval: 300s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
